### ISSUE TITLE
Mod b-from-group

### ISSUE THREAD

**Issue by ScorpioCoding** [Zaczero/bootstrap-v4-snippets#16]
Current  'b-form-group' adds the following
```
<div class="form-group">
    <label for="my-input">Text</label>
    <input id="my-input" class="form-control" type="text">
 </div>
```
Is there a posibility to change input id to name or add the name property.
the name property is used laravel form handleling and cte changing defeats the purpose of using snippets
Iether
```
<div class="form-group">
    <label for="my-input">Text</label>
    <input name="my-input" class="form-control" type="text">
 </div>
```

or

```
<div class="form-group">
    <label for="my-input">Text</label>
    <input id="my-input" name="my-input" class="form-control" type="text">
 </div>
```

**Comment by Zaczero** [comment]
Yeah, I had that idea for a while now in my head.
I will add those name attributes 👍

**Comment by Zaczero** [comment]
Added in 8e00dd1b8e66a4f1278dc3863999fd9b7c6cb965
