### ISSUE TITLE
Broken Preview Link

### ISSUE THREAD

**Issue by eserdinyo** [Zaczero/bootstrap-v4-snippets#20]
Preview link doesn't work on vscode and chrome.

**Comment by Zaczero** [comment]
Hey there!
What preview link are we talking about?

**Comment by eserdinyo** [comment]
The link in VsCode extension page.

**Comment by Zaczero** [comment]
I still don't know what preview link you have on your mind.
https://i.imgur.com/z7A9kzW.mp4

Are we talking about the "link" on the preview .GIF on GitHub? If yes then it's being added by GitHub itself and it's not intended to be a link in any way. GitHub is just linking it to the CDN file. In README.md you can see there is no link on the preview .GIF:

![link vs inline image](https://i.imgur.com/FFvT4ss.png)

*the same 'link' now appears on the image above but it's not the actual link, it's just an image*

**Comment by eserdinyo** [comment]
Sorry. I forgot imgur is forbidden in our contry :(

**Comment by Zaczero** [comment]
Here you go _(mp4 packed into the zip)_:
[MP4.zip](https://github.com/Zaczero/bootstrap-v4-snippets/files/3479078/ZvewmuB4iq.zip)
