### ISSUE TITLE
Doesn't work in vscode 1.37

### ISSUE THREAD

**Issue by yakubenko** [Zaczero/bootstrap-v4-snippets#21]
Hi! Thank you for the extension. Unfortunately, I couldn't get it working as it described in the README file. The "Install and start using" method does not seem to work. I use the latest version of VSCODE and tested the extension on twig, html, vue files but it didn't work.
This is what I've done to make it work. Copied all snippets from this repository and pasted them here Preferences: Configure user snippets > twig. Please, have a look.

```
Version: 1.37.0
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T01:24:14.598Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-34-generic
```

**Comment by Zaczero** [comment]
*Hello there,*

Maybe it's a compatibility issue with some of your other extensions or settings.
Could you provide me a list of extensions you are using and settings.json file?
Screenshot of extensions will do as well so you don't have to copy and paste all of theme here.

![](https://i.imgur.com/NW99VZe.png)

*aka. i need steps to reproduce it --*

**Comment by tzhang-dev** [comment]
Hi, I find this issue since im facing a same bug. I tried to disable some of installed plugins and after i disabled a css sinppets, which is `ecmel.vscode-html-css`, and your extension worked.
Hopefully this may provide clues.
