### ISSUE TITLE
Navbar snippet update: navbar-dark class not working

### ISSUE THREAD

**Issue by counthavoc** [Zaczero/bootstrap-v4-snippets#22]
The b-navbar snippet needs an update.
The class navbar-dark does not work with the current build as the anchor element on line 2 is missing `href="#"`.

Please change line 2 to the following: 
`<a class="navbar-brand" href="#">Navbar</a>`

Additionally could you guys add a standard link between line 10 & 11? It would make it easier to copy lines when adding additional links to the navbar:
```
<li class="nav-item">
<a class="nav-link" href="#">Link</a>
</li>
```

**Comment by Zaczero** [comment]
Thanks for reporting the issue 👍 👍
