### ISSUE TITLE
Support for php and blade

### ISSUE THREAD

**Issue by wpsix** [Zaczero/bootstrap-v4-snippets#3]
Man, this is really awesome but can you add support for php and blade because now I am only able to use it in html.

**Comment by wpsix** [comment]
Ok, just figured it out that I can use your snippet as a user snippet too.

**Comment by Zaczero** [comment]
It should work with php files even if it's HTML snippet. I'm coding mostly in php :)

**Comment by medzhidov** [comment]
> It should work with php files even if it's HTML snippet. I'm coding mostly in php :)

It doesn't work with .blade.php files. But it will cool, if it will work with them. Thanks

**Comment by Zaczero** [comment]
The new version *(0.2)* of the snippets is now supporting `.blade.php` files :+1:
