### ISSUE TITLE
Why doesn't snippets have aria attributes?

### ISSUE THREAD

**Issue by hunkjazz** [Zaczero/bootstrap-v4-snippets#4]
This is something important, even more for component layouts like those in Bootstrap.

Can I PR a set of snippets using aria attributes?

**Comment by Zaczero** [comment]
Sure :)
Just edit the corresponding HTML source files.

I just don't have any experience with aria and didn't want to make a mess where some controls would have the aria attr and some wouldn't.

**Comment by hunkjazz** [comment]
Problem might be solved in part with [this PR](https://github.com/Zaczero/bootstrap-v4-snippets/pull/6).
