### ISSUE TITLE
How can I build and test my modifications?

### ISSUE THREAD

**Issue by hunkjazz** [Zaczero/bootstrap-v4-snippets#5]
I've made some modifications, though I don't want to PR before testing. I'm aware that this is possible, but I just can't figure it out.

**Comment by Zaczero** [comment]
1. You must install .NET Core 2.2 *(or newer)*
2. Open this directory https://github.com/Zaczero/bootstrap-v4-snippets/tree/master/bootstrap-v4-snippets-build/bootstrap-v4-snippets-build/bin/Release/netcoreapp2.2 on your pc
3. Open command prompt in this directory *(Shift + Right click -> Launch Command Window)*
4. Type: `dotnet bootstrap-v4-snippets-build.dll` and wait
5. Now open this file: https://github.com/Zaczero/bootstrap-v4-snippets/blob/master/bootstrap-v4-snippets/snippets/snippets.json and copy it's content
6. In VS Code click `F1` key and search for *Preferences: Configure User Snippets* > *html.json* and paste it there

**Comment by JLammeer** [comment]
Worked perfectly! Thank you so much!

Besides that, I'd recommend to create a "Contributing Guidelines" section, in the `README.md` file. It could refer to this issue and ask for devs to use 4 spaces tab, for example.

**Comment by hunkjazz** [comment]
Worked perfectly! Thank you so much!

Besides that, I'd recommend to create a "Contributing Guidelines" section, in the `README.md` file. It could refer to this issue and ask for devs to use 4 spaces tab, for example.
