### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by OpsecGuy** [Zaczero/bootstrap-v4-snippets#7]
Where is .exe can't run.

**Comment by Zaczero** [comment]
It's a NET Core 2.2 .dll (in command prompt type `dotnet bootstrap-v4-snippets-build.dll`).

It's stored here:
https://github.com/Zaczero/bootstrap-v4-snippets/tree/master/bootstrap-v4-snippets-build/bootstrap-v4-snippets-build/bin/Release/netcoreapp2.2
