### ISSUE TITLE
Support single page component .vue files?

### ISSUE THREAD

**Issue by threeFatCat** [Zaczero/bootstrap-v4-snippets#8]
Is it possible to make this work in .vue files? Thanks.

**Comment by rant1989** [comment]
F1 -> preference configure user snippets -> 
then serch vue-html 
then copy this file to there
https://github.com/Zaczero/bootstrap-v4-snippets/blob/master/bootstrap-v4-snippets/snippets/snippets.json

**Comment by Zaczero** [comment]
Added in https://github.com/Zaczero/bootstrap-v4-snippets/commit/21bc1df2b1b84375b9e2459c90f8d501532f0730 *(requires additional verification)*

**Comment by mreduar** [comment]
How can I make this work? It doesn't work for me. https://prnt.sc/rt0gnm

**Comment by Zaczero** [comment]
> 
> 
> How can I make this work? It doesn't work for me. https://prnt.sc/rt0gnm

What is your active file type?

![image](https://user-images.githubusercontent.com/10835147/78463786-4248ae00-76e1-11ea-8d7f-2276a050e5f4.png)

**Comment by mreduar** [comment]
> > How can I make this work? It doesn't work for me. https://prnt.sc/rt0gnm
> 
> What is your active file type?
> 
> ![image](https://user-images.githubusercontent.com/10835147/78463786-4248ae00-76e1-11ea-8d7f-2276a050e5f4.png)

Vue
https://prnt.sc/rt7ira

**Comment by mreduar** [comment]
Shall I open a new issue with this?

**Comment by Zaczero** [comment]
> 
> 
> Shall I open a new issue with this?

Yeah go for it
